#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM --platform=$TARGETARCH mcr.microsoft.com/dotnet/aspnet:8.0.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0.100-1-bookworm-slim AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Api.GPT/Api.GPT.csproj", "Api.GPT/"]
COPY ["Auth.Database/Auth.Database.csproj", "Auth.Database/"]
COPY ["Crosscutting/Crosscutting.csproj", "Crosscutting/"]
COPY ["DiscordSaga.Components/DiscordSaga.Components.csproj", "DiscordSaga.Components/"]
COPY ["gpt.application/Gpt.application.csproj", "gpt.application/"]
COPY ["Gpt.Components/Gpt.Components.csproj", "Gpt.Components/"]
COPY ["Gpt.Infrastructure/Gpt.Infrastructure.csproj", "Gpt.Infrastructure/"]
COPY ["BoundBot.Connection/BoundBot.Connection.csproj", "BoundBot.Connection/"]
COPY ["LoggingService.Components/LoggingService.Components.csproj", "LoggingService.Components/"]
RUN dotnet restore "Api.GPT/Api.GPT.csproj"
COPY . .
WORKDIR "/src/Api.GPT"
RUN dotnet build "Api.GPT.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
RUN dotnet publish "Api.GPT.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Api.GPT.dll"]